[workspace]
resolver = "3"
members = ["crates/vtui-core","crates/vtui-macros"]

[package]
name = "vtui"
version = "0.1.0-alpha"
edition = "2024"
description = "A simple event-driven terminal UI framework"
license = "MIT"

[features]
default = ["crossterm"]
crossterm = ["dep:crossterm", "ratatui/crossterm"]

[dependencies]
crossterm = { version = "0.29.0", optional = true }
ratatui = { version = "0.30.0", default-features = false }
thiserror = "2.0.17"
vtui-core = { version = "0.1.0-alpha", path = "crates/vtui-core" }
vtui-macros = { version = "0.1.0-alpha", path = "crates/vtui-macros" }
