[workspace]
resolver = "3"
members = ["crates/vtui-core","crates/vtui-macros"]

[package]
name = "vtui"
version = "0.1.0-alpha"
edition = "2024"
description = "A simple event-driven terminal UI framework"
license = "MIT"

[dependencies]
anyhow = "1.0.100"
crossterm = "0.29.0"
ratatui = "0.30.0"
vtui-core = { version = "0.1.0-alpha", path = "crates/vtui-core" }
vtui-macros = { version = "0.1.0-alpha", path = "crates/vtui-macros" }
