[package]
name = "vtui-macros"
version = "0.1.0"
edition = "2024"
description = "A simple terminal UI framework"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.105"
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }
