[package]
name = "vtui-macros"
version = "0.1.0-alpha"
edition = "2024"
description = "A simple event-driven terminal UI framework"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
quote = "1.0.42"
syn = { version = "2.0.111", features = ["full"] }
