[package]
name = "vtui-core"
version = "0.1.0-beta"
edition = "2024"
description = "A simple terminal UI framework"
license = "MIT"

[dependencies]
ratatui = { version = "0.30.0", default-features = false }
thiserror = "2.0.17"
