[package]
name = "vtui-macros"
version = "0.4.2"
edition = "2024"
description = "A simple terminal UI framework"
license = "MIT"

[lib]
proc-macro = true

[dependencies]
proc-macro2 = "1.0.106"
quote = "1.0.44"
syn = { version = "2.0.114", features = ["full"] }
